<template>
  <!-- TOOLS -->
  <div class="flex flex-wrap gap-1">
    <img
      src="@/assets/icons/svg/javascript-original.svg"
      title="Javascript"
      alt="Javascript"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/typescript-original.svg"
      title="Typescript"
      alt="Typescript"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/html5-original.svg"
      title="HTML5"
      alt="HTML5"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/css3-original.svg"
      title="CSS3"
      alt="CSS3"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/kotlin-original.svg"
      title="Kotlin"
      alt="Kotlin"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/python-original.svg"
      title="Python"
      alt="Python"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/vuejs-original.svg"
      title="Vue"
      alt="Vue"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/vite-original.svg"
      title="Vite"
      alt="Vite"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/nuxtjs-original.svg"
      title="Nuxt"
      alt="Nuxt"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/tailwindcss-plain.svg"
      title="Tailwind"
      alt="Tailwind"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/nodejs-original-wordmark.svg"
      title="Node"
      alt="Node"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/nestjs-plain.svg"
      title="Nest"
      alt="Nest"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/express-original-wordmark.svg"
      title="express"
      alt="express"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/postgresql-original.svg"
      title="Postgresql"
      alt="Postgresql"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/mongodb-original-wordmark.svg"
      title="mongoDB"
      alt="MongoDB"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/docker-original.svg"
      title="Docker"
      alt="Docker"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/firebase-plain.svg"
      title="Firebase"
      alt="Firebase"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/graphql-plain.svg"
      title="GraphQL"
      alt="GraphQL"
      width="35"
      height="35"
    />
    <img
      src="@/assets/icons/svg/django-original.svg"
      title="Django"
      alt="Django"
      width="35"
      height="35"
    />
  </div>
</template>
